version: "3.8"

services:
  mcs-gateway:
    build:
      context: gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_HOST=mcs-user:3001
    networks:
      - mcs

  mcs-user:
    build:
      context: user
    environment:
      - PORT=3001
    networks:
      - mcs

networks:
  mcs: {}
